# Generated by Django 5.2.4 on 2025-07-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mamamboga',
            name='pin',
            field=models.CharField(max_length=32),
        ),
    ]
