# Generated by Django 5.2.4 on 2025-07-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsessions',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
