# Generated by Django 5.2.4 on 2025-07-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsessions',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingsessions',
            name='registered',
            field=models.IntegerField(null=True),
        ),
    ]
