# Generated by Django 5.2.3 on 2025-06-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_mamamboga_name_mamamboga_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mamamboga',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
