# Generated by Django 5.2.3 on 2025-07-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_mamamboga_id_alter_stakeholder_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='phone_number',
        ),
    ]
