# Generated by Django 5.2.3 on 2025-06-20 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mamamboga',
            fields=[
                ('mamamboga_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSessions',
            fields=[
                ('session_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMembers',
            fields=[
                ('membership_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('joined_date', models.DateTimeField(blank=True, null=True)),
                ('left_date', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='communities.community')),
                ('mamamboga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to='communities.mamamboga')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities_created', to='communities.mamamboga'),
        ),
        migrations.CreateModel(
            name='TrainingRegistration',
            fields=[
                ('registration_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_registrations', to='communities.community')),
                ('mamamboga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_registrations', to='communities.mamamboga')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='communities.trainingsessions')),
            ],
        ),
    ]
