# Generated by Django 5.2.3 on 2025-06-23 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities_created', to='users.mamamboga'),
        ),
        migrations.AlterField(
            model_name='trainingregistration',
            name='mamamboga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_registrations', to='users.mamamboga'),
        ),
        migrations.AlterField(
            model_name='communitymembers',
            name='mamamboga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to='users.mamamboga'),
        ),
        migrations.DeleteModel(
            name='Mamamboga',
        ),
    ]
