# Generated by Django 5.2.3 on 2025-06-23 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_mamamboga_stock'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='mamamboga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='users.mamamboga'),
        ),
        migrations.DeleteModel(
            name='Mamamboga',
        ),
    ]
