# Generated by Django 5.2.4 on 2025-07-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock_mamamboga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VEG', 'Vegetable'), ('FRUIT', 'Fruit')], max_length=20),
        ),
    ]
