# Generated by Django 5.2.3 on 2025-07-03 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_product_category_remove_product_tags_and_more'),
        ('users', '0003_alter_mamamboga_id_alter_stakeholder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='mamamboga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='users.mamamboga'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VEG', 'Vegetable'), ('FRUIT', 'Fruit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
