# Generated by Django 5.2.3 on 2025-07-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_order_community_alter_order_mamamboga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
